version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_apilogin
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api_login       # Nome do banco de dados
      POSTGRES_USER: api_login_user      # Nome do usuário
      POSTGRES_PASSWORD: api_login_pass  # Senha do usuário
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: